apiVersion: stack.zncdata.net/v1alpha1
kind: ArgoWorkFlow
metadata:
  labels:
    app.kubernetes.io/name: argoworkflow
    app.kubernetes.io/instance: argoworkflow-sample
    app.kubernetes.io/part-of: argo-workflow-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: argo-workflow-operator
  name: argoworkflow-sample
spec:
  # TODO(user): Add fields here
